<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IcyShippedLibrary>true</IcyShippedLibrary>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <RootNamespace>Icy</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Themes\DefaultTheme.xml" />
  </ItemGroup>
</Project>
