<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IcyShippedLibrary>true</IcyShippedLibrary>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RootNamespace>Icy.MonoGame</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IcyUI\IcyUI.csproj" />
  </ItemGroup>

</Project>
