<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Icy.StrideSample</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Core" Version="4.2.0.2122" />
    <PackageReference Include="Stride.Engine" Version="4.2.0.2122" />
    <PackageReference Include="Stride.Graphics" Version="4.2.0.2122" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IcyUI.Stride\IcyUI.Stride.csproj" />
    <ProjectReference Include="..\IcyUI\IcyUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared Samples\ControlsDemo.cs" Link="ControlsDemo.cs" />
    <Compile Include="..\Shared Samples\StylesDemo.cs" Link="StylesDemo.cs" />
    <Compile Include="..\Shared Samples\MarkupDemo.cs" Link="MarkupDemo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\Fonts\Airfool.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
